name: Test

on: push

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash --noprofile --norc -e -o pipefail -o igncr {0}
    env:
      PATH: C:\cygwin\bin
      GIT_REV: ef05e8bda

    steps:
      - name: Install Cygwin packages
        uses: cygwin/cygwin-install-action@v2
        with:
          packages: autoconf automake cocom curl cygport diffutils findutils git gcc-core gcc-g++ gettext gettext-devel gnupg gnupg2 libcurl-devel libexpat-devel libiconv libiconv-devel libpcre2-devel libssl-devel make mingw64-x86_64-gcc-g++ mingw64-x86_64-zlib perl perl-Authen-SASL perl-DBD-SQLite perl-IO-Socket-SSL perl-IO-Tty perl-MailTools perl-Net-SMTP-SSL perl-TermReadKey perl-Test-Harness perl-XML-SAX perl-YAML pkg-config subversion-perl time xz zlib-devel
          site: http://ctm.crouchingtigerhiddenfruitbat.org/pub/cygwin/circa/64bit/2021/10/28/174906
          check-sig: false

      - name: Manually configure safe.directory
        run: git config --global --add safe.directory '*'

      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Build Cygwin
        run: cygport cygwin.cygport download prep compile test install

      - name: Separate out cygwin1.dll and install everything else
        run: |
          mv cygwin-*.x86_64/inst/usr/bin/cygwin1.dll ./
          cd cygwin-*.x86_64/inst
          find usr etc -type f -exec bash -c 'for f; do mkdir -p /"$(dirname "$f")" && cp "$f" /"$f"; done' - {} +

      - name: Install cygwin1.dll
        shell: pwsh  # Can't use Cygwin Bash as that would involve using the cygwin1.dll that's being overwritten
        run: Copy-Item -Force .\cygwin1.dll C:\cygwin\bin\cygwin1.dll

      - name: Confirm the build is correctly installed
        shell: bash --noprofile --norc -x -e -o pipefail -o igncr {0}
        run: |
          sha1sum cygwin1.dll "$(which cygwin1.dll)"
          diff <(cd cygwin-*.x86_64 && find . -type f -exec bash -c 'for f; do sha1sum "$f"; done' - {} +) <(cd cygwin-*.x86_64 && find . -type f -exec bash -c 'cd / && for f; do sha1sum "$f"; done' - {} +)

      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          set-safe-directory: false
          repository: git/git
          ref: main
          path: git

      - name: Build Cygwin Git
        run: cd git && make -j3

      - name: Test t0301
        run: cd git/t && ./t0301-*.sh
